version: "3.8"
services:
  caddy-gen:
    container_name: caddy2-gen
    build: ..
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./caddy-info:/data/caddy
      - ./caddy_global_options:/tmp/caddy_global_options
    ports:
      - "80:80"
      - "443:443"
    environment:
      CADDY_SNIPPET: /tmp/caddy_global_options
    depends_on:
      - whoami
      - whoami2

  whoami:
    image: "katacoda/docker-http-server:v1"
    labels:
      - "virtual.host=test1.localhost"

  whoami2:
    image: "katacoda/docker-http-server:v2"
    labels:
      - "virtual.host=myapp.com" # your domain
      - "virtual.alias=www.myapp.com" # alias for your domain (optional)
      - "virtual.port=80" # exposed port of this container
      - "virtual.tls-email=admin@myapp.com" # ssl is now on
