name: CI-arm64

on:
  push:
    branches: [master]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWD }}

      - uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'

      - uses: docker/setup-buildx-action@v2    

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with: 
          context: .
          push: true
          tags: |
            oamigo/caddy-gen:v2
